### ISSUE TITLE
Generating the Bounding Box label

### ISSUE THREAD

**Issue by MrOCR** [watersink/ocrsegment#2]
@watersink How can I generate the `.txt` bounding box file for an image?

**Comment by watersink** [comment]
try this, https://github.com/tzutalin/labelImg

**Comment by MrOCR** [comment]
@watersink can you include `/save/ocrseg.ckpt-1000` in your project, so that we can test the segmentation.

**Comment by MrOCR** [comment]
@watersink Thank you,
The [labelImg](https://github.com/tzutalin/labelImg) is working well. 
Another suggestion is [Alp’s Labeling Tool (ALT)](https://alpslabel.wordpress.com/2017/01/26/alt/).

Thanks

**Comment by watersink** [comment]
@MrOCR https://github.com/opencv/cvat
