### ISSUE TITLE
Blank output !

### ISSUE THREAD

**Issue by MrOCR** [watersink/ocrsegment#4]

**Comment by MrOCR** [comment]
@lvaleriu Ocrsegment seems to be incomplete, my suggestion for you is to search other projects.

**Comment by lvaleriu** [comment]
I've just fixed the incompatible shapes issue (had to modify the resize parameters of images/labels) and trained the network for 8K iterations and got a nice result:
![image](https://user-images.githubusercontent.com/927999/50305428-11fce200-0493-11e9-91b6-e344859850c7.png)

**Comment by MrOCR** [comment]
@lvaleriu send the original image.

**Comment by lvaleriu** [comment]
The image is ./make_training_labels/W001.png.

**Comment by MrOCR** [comment]
@lvaleriu can you share your latest training results, how many iterations have you reached.

Though I would still urge you to use the original project https://github.com/NVlabs/ocropus3 it contains ocroseg which can also extract the lines.
